# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'danser.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(701, 784)
        Dialog.setStyleSheet(u"QDialog {\n"
"background-color: rgb(179, 179, 179);}\n"
"QGroupBox {\n"
"background-color: rgb(255, 255, 255);}")
        self.settings = QTabWidget(Dialog)
        self.settings.setObjectName(u"settings")
        self.settings.setGeometry(QRect(0, 270, 701, 141))
        self.settings.setStyleSheet(u"QTabWidget {\n"
"background-color: rgb(211, 211, 211);}\n"
"")
        self.tab_18 = QWidget()
        self.tab_18.setObjectName(u"tab_18")
        self.vsync = QCheckBox(self.tab_18)
        self.vsync.setObjectName(u"vsync")
        self.vsync.setGeometry(QRect(10, 50, 75, 20))
        self.fullscreenbutton = QCheckBox(self.tab_18)
        self.fullscreenbutton.setObjectName(u"fullscreenbutton")
        self.fullscreenbutton.setGeometry(QRect(10, 10, 91, 21))
        self.fullscreenbutton.setChecked(True)
        self.showfps = QCheckBox(self.tab_18)
        self.showfps.setObjectName(u"showfps")
        self.showfps.setGeometry(QRect(10, 30, 75, 20))
        self.showfps.setChecked(True)
        self.label_36 = QLabel(self.tab_18)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(100, 10, 49, 21))
        self.fpscap = QSpinBox(self.tab_18)
        self.fpscap.setObjectName(u"fpscap")
        self.fpscap.setGeometry(QRect(150, 10, 42, 22))
        self.fpscap.setMaximum(1000)
        self.fpscap.setSingleStep(30)
        self.fpscap.setValue(120)
        self.label_37 = QLabel(self.tab_18)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(100, 40, 49, 21))
        self.msaa = QSpinBox(self.tab_18)
        self.msaa.setObjectName(u"msaa")
        self.msaa.setGeometry(QRect(150, 40, 42, 22))
        self.msaa.setMaximum(10)
        self.msaa.setSingleStep(2)
        self.msaa.setValue(0)
        self.usepersistentbuffers = QCheckBox(self.tab_18)
        self.usepersistentbuffers.setObjectName(u"usepersistentbuffers")
        self.usepersistentbuffers.setGeometry(QRect(10, 70, 141, 20))
        self.label_46 = QLabel(self.tab_18)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(200, 40, 41, 21))
        self.width = QSpinBox(self.tab_18)
        self.width.setObjectName(u"width")
        self.width.setGeometry(QRect(250, 10, 121, 22))
        self.width.setMaximum(1920)
        self.width.setSingleStep(10)
        self.width.setValue(1920)
        self.label_47 = QLabel(self.tab_18)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(200, 10, 41, 21))
        self.height = QSpinBox(self.tab_18)
        self.height.setObjectName(u"height")
        self.height.setGeometry(QRect(250, 40, 121, 21))
        self.height.setMaximum(1080)
        self.height.setSingleStep(10)
        self.height.setValue(1080)
        self.label_48 = QLabel(self.tab_18)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(380, 40, 81, 21))
        self.winwidth = QSpinBox(self.tab_18)
        self.winwidth.setObjectName(u"winwidth")
        self.winwidth.setGeometry(QRect(470, 10, 121, 22))
        self.winwidth.setMaximum(1920)
        self.winwidth.setSingleStep(10)
        self.winwidth.setValue(1920)
        self.winheight = QSpinBox(self.tab_18)
        self.winheight.setObjectName(u"winheight")
        self.winheight.setGeometry(QRect(470, 40, 121, 21))
        self.winheight.setMaximum(1080)
        self.winheight.setSingleStep(10)
        self.winheight.setValue(1080)
        self.label_49 = QLabel(self.tab_18)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(380, 10, 81, 21))
        self.settings.addTab(self.tab_18, "")
        self.tab_17 = QWidget()
        self.tab_17.setObjectName(u"tab_17")
        self.groupBox_2 = QGroupBox(self.tab_17)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(430, 10, 261, 91))
        self.enablerainbow = QCheckBox(self.groupBox_2)
        self.enablerainbow.setObjectName(u"enablerainbow")
        self.enablerainbow.setGeometry(QRect(10, 20, 75, 20))
        self.enablerainbow.setChecked(True)
        self.trailstyle = QSpinBox(self.tab_17)
        self.trailstyle.setObjectName(u"trailstyle")
        self.trailstyle.setGeometry(QRect(80, 10, 42, 22))
        self.trailstyle.setMaximum(4)
        self.trailstyle.setValue(1)
        self.label_32 = QLabel(self.tab_17)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 10, 61, 21))
        self.label_33 = QLabel(self.tab_17)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 40, 71, 21))
        self.style23speed = QDoubleSpinBox(self.tab_17)
        self.style23speed.setObjectName(u"style23speed")
        self.style23speed.setGeometry(QRect(80, 40, 41, 22))
        self.style23speed.setMaximum(1.000000000000000)
        self.style23speed.setSingleStep(0.010000000000000)
        self.style23speed.setValue(0.180000000000000)
        self.settings.addTab(self.tab_17, "")
        self.tab_19 = QWidget()
        self.tab_19.setObjectName(u"tab_19")
        self.resultscreen = QCheckBox(self.tab_19)
        self.resultscreen.setObjectName(u"resultscreen")
        self.resultscreen.setGeometry(QRect(10, 10, 91, 20))
        self.resultscreen.setChecked(True)
        self.label_38 = QLabel(self.tab_19)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 50, 101, 21))
        self.resultscreentime = QSpinBox(self.tab_19)
        self.resultscreentime.setObjectName(u"resultscreentime")
        self.resultscreentime.setGeometry(QRect(120, 50, 42, 22))
        self.resultscreentime.setMaximum(10)
        self.resultscreentime.setValue(5)
        self.label_39 = QLabel(self.tab_19)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 70, 111, 21))
        self.flashlightdim = QSpinBox(self.tab_19)
        self.flashlightdim.setObjectName(u"flashlightdim")
        self.flashlightdim.setGeometry(QRect(120, 70, 42, 22))
        self.flashlightdim.setValue(1)
        self.warningerrors = QCheckBox(self.tab_19)
        self.warningerrors.setObjectName(u"warningerrors")
        self.warningerrors.setGeometry(QRect(10, 30, 111, 20))
        self.warningerrors.setChecked(True)
        self.settings.addTab(self.tab_19, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.xkey = QKeySequenceEdit(self.tab_7)
        self.xkey.setObjectName(u"xkey")
        self.xkey.setGeometry(QRect(90, 0, 113, 22))
        self.zkey = QKeySequenceEdit(self.tab_7)
        self.zkey.setObjectName(u"zkey")
        self.zkey.setGeometry(QRect(90, 30, 113, 22))
        self.rkey = QKeySequenceEdit(self.tab_7)
        self.rkey.setObjectName(u"rkey")
        self.rkey.setGeometry(QRect(90, 60, 113, 22))
        self.ckey = QKeySequenceEdit(self.tab_7)
        self.ckey.setObjectName(u"ckey")
        self.ckey.setGeometry(QRect(90, 90, 113, 22))
        self.label_25 = QLabel(self.tab_7)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(0, 0, 49, 20))
        self.label_26 = QLabel(self.tab_7)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(0, 30, 49, 20))
        self.label_27 = QLabel(self.tab_7)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(0, 60, 49, 20))
        self.label_28 = QLabel(self.tab_7)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 90, 49, 20))
        self.mouse = QCheckBox(self.tab_7)
        self.mouse.setObjectName(u"mouse")
        self.mouse.setGeometry(QRect(220, 0, 111, 20))
        self.mousesensivity = QDoubleSpinBox(self.tab_7)
        self.mousesensivity.setObjectName(u"mousesensivity")
        self.mousesensivity.setGeometry(QRect(320, 20, 62, 22))
        self.mousesensivity.setDecimals(1)
        self.mousesensivity.setMaximum(1.000000000000000)
        self.mousesensivity.setSingleStep(0.100000000000000)
        self.mousesensivity.setValue(1.000000000000000)
        self.label_29 = QLabel(self.tab_7)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(220, 20, 101, 21))
        self.mousehighprecision = QCheckBox(self.tab_7)
        self.mousehighprecision.setObjectName(u"mousehighprecision")
        self.mousehighprecision.setGeometry(QRect(220, 40, 141, 20))
        self.settings.addTab(self.tab_7, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.loadstoryboards = QCheckBox(self.tab_3)
        self.loadstoryboards.setObjectName(u"loadstoryboards")
        self.loadstoryboards.setGeometry(QRect(0, 10, 121, 20))
        self.loadstoryboards.setChecked(True)
        self.loadvideos = QCheckBox(self.tab_3)
        self.loadvideos.setObjectName(u"loadvideos")
        self.loadvideos.setGeometry(QRect(0, 30, 121, 20))
        self.flashtobeat = QCheckBox(self.tab_3)
        self.flashtobeat.setObjectName(u"flashtobeat")
        self.flashtobeat.setGeometry(QRect(0, 50, 121, 20))
        self.flashtobeat.setChecked(True)
        self.settings.addTab(self.tab_3, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.bloom = QCheckBox(self.tab)
        self.bloom.setObjectName(u"bloom")
        self.bloom.setGeometry(QRect(0, 10, 61, 20))
        self.bloom.setChecked(True)
        self.bloomtobeat = QCheckBox(self.tab)
        self.bloomtobeat.setObjectName(u"bloomtobeat")
        self.bloomtobeat.setGeometry(QRect(0, 30, 111, 20))
        self.bloomtobeat.setChecked(True)
        self.bloomtobeatadd = QDoubleSpinBox(self.tab)
        self.bloomtobeatadd.setObjectName(u"bloomtobeatadd")
        self.bloomtobeatadd.setEnabled(True)
        self.bloomtobeatadd.setGeometry(QRect(100, 30, 41, 22))
        self.bloomtobeatadd.setDecimals(1)
        self.bloomtobeatadd.setMaximum(1.000000000000000)
        self.bloomtobeatadd.setSingleStep(0.100000000000000)
        self.bloomtobeatadd.setValue(0.300000000000000)
        self.bloomblur = QDoubleSpinBox(self.tab)
        self.bloomblur.setObjectName(u"bloomblur")
        self.bloomblur.setEnabled(True)
        self.bloomblur.setGeometry(QRect(230, 10, 41, 22))
        self.bloomblur.setDecimals(1)
        self.bloomblur.setMaximum(1.000000000000000)
        self.bloomblur.setSingleStep(0.100000000000000)
        self.bloomblur.setValue(0.600000000000000)
        self.bloompower = QDoubleSpinBox(self.tab)
        self.bloompower.setObjectName(u"bloompower")
        self.bloompower.setEnabled(True)
        self.bloompower.setGeometry(QRect(230, 40, 41, 22))
        self.bloompower.setDecimals(1)
        self.bloompower.setMaximum(1.000000000000000)
        self.bloompower.setSingleStep(0.100000000000000)
        self.bloompower.setValue(0.700000000000000)
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 40, 49, 16))
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(150, 10, 49, 16))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(150, 70, 61, 16))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.bloomthreshold = QDoubleSpinBox(self.tab)
        self.bloomthreshold.setObjectName(u"bloomthreshold")
        self.bloomthreshold.setEnabled(True)
        self.bloomthreshold.setGeometry(QRect(230, 70, 41, 22))
        self.bloomthreshold.setDecimals(1)
        self.bloomthreshold.setMaximum(1.000000000000000)
        self.bloomthreshold.setSingleStep(0.100000000000000)
        self.settings.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.blur = QCheckBox(self.tab_2)
        self.blur.setObjectName(u"blur")
        self.blur.setGeometry(QRect(0, 10, 75, 20))
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(500, 0, 191, 111))
        self.blurintro = QDoubleSpinBox(self.groupBox)
        self.blurintro.setObjectName(u"blurintro")
        self.blurintro.setGeometry(QRect(120, 20, 62, 22))
        self.blurintro.setDecimals(1)
        self.blurintro.setMaximum(1.000000000000000)
        self.blurintro.setSingleStep(0.100000000000000)
        self.blurnormal = QDoubleSpinBox(self.groupBox)
        self.blurnormal.setObjectName(u"blurnormal")
        self.blurnormal.setGeometry(QRect(120, 50, 62, 22))
        self.blurnormal.setDecimals(1)
        self.blurnormal.setMaximum(1.000000000000000)
        self.blurnormal.setSingleStep(0.100000000000000)
        self.blurnormal.setValue(0.600000000000000)
        self.blurbreaks = QDoubleSpinBox(self.groupBox)
        self.blurbreaks.setObjectName(u"blurbreaks")
        self.blurbreaks.setGeometry(QRect(120, 80, 62, 22))
        self.blurbreaks.setDecimals(1)
        self.blurbreaks.setMaximum(1.000000000000000)
        self.blurbreaks.setSingleStep(0.100000000000000)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 50, 49, 16))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 20, 49, 16))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 80, 49, 16))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.settings.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.dimanim = QGroupBox(self.tab_4)
        self.dimanim.setObjectName(u"dimanim")
        self.dimanim.setGeometry(QRect(500, 0, 191, 111))
        self.dimintro = QDoubleSpinBox(self.dimanim)
        self.dimintro.setObjectName(u"dimintro")
        self.dimintro.setGeometry(QRect(120, 20, 62, 22))
        self.dimintro.setDecimals(1)
        self.dimintro.setMaximum(1.000000000000000)
        self.dimintro.setSingleStep(0.100000000000000)
        self.dimnormal = QDoubleSpinBox(self.dimanim)
        self.dimnormal.setObjectName(u"dimnormal")
        self.dimnormal.setGeometry(QRect(120, 50, 62, 22))
        self.dimnormal.setDecimals(1)
        self.dimnormal.setMaximum(1.000000000000000)
        self.dimnormal.setSingleStep(0.100000000000000)
        self.dimnormal.setValue(0.600000000000000)
        self.dimbreaks = QDoubleSpinBox(self.dimanim)
        self.dimbreaks.setObjectName(u"dimbreaks")
        self.dimbreaks.setGeometry(QRect(120, 80, 62, 22))
        self.dimbreaks.setDecimals(1)
        self.dimbreaks.setMaximum(1.000000000000000)
        self.dimbreaks.setSingleStep(0.100000000000000)
        self.label_7 = QLabel(self.dimanim)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 50, 49, 16))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.dimanim)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 20, 49, 16))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.dimanim)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 80, 49, 16))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.settings.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_10 = QLabel(self.tab_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 40, 49, 16))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.paralaxspeed = QDoubleSpinBox(self.tab_5)
        self.paralaxspeed.setObjectName(u"paralaxspeed")
        self.paralaxspeed.setGeometry(QRect(100, 40, 62, 22))
        self.paralaxspeed.setDecimals(1)
        self.paralaxspeed.setMaximum(1.000000000000000)
        self.paralaxspeed.setSingleStep(0.100000000000000)
        self.paralaxspeed.setValue(0.600000000000000)
        self.label_11 = QLabel(self.tab_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 10, 49, 16))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.paralaxamount = QDoubleSpinBox(self.tab_5)
        self.paralaxamount.setObjectName(u"paralaxamount")
        self.paralaxamount.setGeometry(QRect(100, 10, 62, 22))
        self.paralaxamount.setDecimals(1)
        self.paralaxamount.setMaximum(1.000000000000000)
        self.paralaxamount.setSingleStep(0.100000000000000)
        self.paralaxamount.setValue(0.100000000000000)
        self.settings.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.triangles = QCheckBox(self.tab_6)
        self.triangles.setObjectName(u"triangles")
        self.triangles.setGeometry(QRect(0, 10, 75, 20))
        self.trianglesshadow = QCheckBox(self.tab_6)
        self.trianglesshadow.setObjectName(u"trianglesshadow")
        self.trianglesshadow.setGeometry(QRect(0, 30, 75, 20))
        self.trianglesshadow.setChecked(True)
        self.trianglesdrawoverblur = QCheckBox(self.tab_6)
        self.trianglesdrawoverblur.setObjectName(u"trianglesdrawoverblur")
        self.trianglesdrawoverblur.setGeometry(QRect(0, 50, 111, 20))
        self.trianglesdrawoverblur.setChecked(True)
        self.trianglesparalaxmultiplier = QDoubleSpinBox(self.tab_6)
        self.trianglesparalaxmultiplier.setObjectName(u"trianglesparalaxmultiplier")
        self.trianglesparalaxmultiplier.setGeometry(QRect(110, 80, 41, 22))
        self.trianglesparalaxmultiplier.setDecimals(1)
        self.trianglesparalaxmultiplier.setMaximum(1.000000000000000)
        self.trianglesparalaxmultiplier.setSingleStep(0.100000000000000)
        self.trianglesparalaxmultiplier.setValue(0.500000000000000)
        self.label_12 = QLabel(self.tab_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 80, 101, 16))
        self.trianglesdensity = QSpinBox(self.tab_6)
        self.trianglesdensity.setObjectName(u"trianglesdensity")
        self.trianglesdensity.setGeometry(QRect(320, 20, 42, 22))
        self.trianglesdensity.setMaximum(10)
        self.trianglesdensity.setValue(1)
        self.trianglesscale = QSpinBox(self.tab_6)
        self.trianglesscale.setObjectName(u"trianglesscale")
        self.trianglesscale.setGeometry(QRect(320, 50, 42, 22))
        self.trianglesscale.setMaximum(10)
        self.trianglesscale.setValue(1)
        self.trianglesspeed = QSpinBox(self.tab_6)
        self.trianglesspeed.setObjectName(u"trianglesspeed")
        self.trianglesspeed.setGeometry(QRect(320, 80, 42, 22))
        self.trianglesspeed.setMaximum(10)
        self.trianglesspeed.setValue(1)
        self.label_13 = QLabel(self.tab_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(250, 20, 51, 21))
        self.label_14 = QLabel(self.tab_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(250, 50, 51, 21))
        self.label_15 = QLabel(self.tab_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(250, 80, 51, 21))
        self.settings.addTab(self.tab_6, "")
        self.tab_20 = QWidget()
        self.tab_20.setObjectName(u"tab_20")
        self.drawspectrum = QCheckBox(self.tab_20)
        self.drawspectrum.setObjectName(u"drawspectrum")
        self.drawspectrum.setGeometry(QRect(10, 10, 51, 20))
        self.drawspectrum.setChecked(True)
        self.groupBox_5 = QGroupBox(self.tab_20)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(500, 0, 191, 111))
        self.drawspectrumintro = QDoubleSpinBox(self.groupBox_5)
        self.drawspectrumintro.setObjectName(u"drawspectrumintro")
        self.drawspectrumintro.setGeometry(QRect(120, 20, 62, 22))
        self.drawspectrumintro.setDecimals(1)
        self.drawspectrumintro.setMaximum(1.000000000000000)
        self.drawspectrumintro.setSingleStep(0.100000000000000)
        self.drawspectrumnormal = QDoubleSpinBox(self.groupBox_5)
        self.drawspectrumnormal.setObjectName(u"drawspectrumnormal")
        self.drawspectrumnormal.setGeometry(QRect(120, 50, 62, 22))
        self.drawspectrumnormal.setDecimals(1)
        self.drawspectrumnormal.setMaximum(1.000000000000000)
        self.drawspectrumnormal.setSingleStep(0.100000000000000)
        self.drawspectrumnormal.setValue(1.000000000000000)
        self.drawspectrumbreaks = QDoubleSpinBox(self.groupBox_5)
        self.drawspectrumbreaks.setObjectName(u"drawspectrumbreaks")
        self.drawspectrumbreaks.setGeometry(QRect(120, 80, 62, 22))
        self.drawspectrumbreaks.setDecimals(1)
        self.drawspectrumbreaks.setMaximum(1.000000000000000)
        self.drawspectrumbreaks.setSingleStep(0.100000000000000)
        self.drawspectrumbreaks.setValue(1.000000000000000)
        self.label_60 = QLabel(self.groupBox_5)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(20, 50, 49, 16))
        self.label_60.setAlignment(Qt.AlignCenter)
        self.label_61 = QLabel(self.groupBox_5)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(20, 20, 49, 16))
        self.label_61.setAlignment(Qt.AlignCenter)
        self.label_72 = QLabel(self.groupBox_5)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(20, 80, 49, 16))
        self.label_72.setAlignment(Qt.AlignCenter)
        self.settings.addTab(self.tab_20, "")
        self.coinfirm = QPushButton(Dialog)
        self.coinfirm.setObjectName(u"coinfirm")
        self.coinfirm.setGeometry(QRect(0, 560, 331, 21))
        self.coinfirm.setStyleSheet(u"QPushButton {\n"
"border-radius: 5px;\n"
"background-color: rgb(202, 202, 202);\n"
"border: 1px solid gray;\n"
"transition: top 1s ease-out 0.5s;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: gray;\n"
"}")
        self.exit = QPushButton(Dialog)
        self.exit.setObjectName(u"exit")
        self.exit.setGeometry(QRect(340, 560, 361, 21))
        self.exit.setStyleSheet(u"QPushButton {\n"
"border-radius: 5px;\n"
"background-color: rgb(202, 202, 202);\n"
"border: 1px solid gray;\n"
"transition: top 1s ease-out 0.5s;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: gray;\n"
"}")
        self.play = QPushButton(Dialog)
        self.play.setObjectName(u"play")
        self.play.setGeometry(QRect(190, 760, 511, 21))
        self.play.setStyleSheet(u"QPushButton {\n"
"border-radius: 5px;\n"
"background-color: rgb(202, 202, 202);\n"
"border: 1px solid gray;\n"
"transition: top 1s ease-out 0.5s;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: gray;\n"
"}")
        self.audio = QGroupBox(Dialog)
        self.audio.setObjectName(u"audio")
        self.audio.setGeometry(QRect(500, 0, 201, 271))
        self.generalvolume = QDoubleSpinBox(self.audio)
        self.generalvolume.setObjectName(u"generalvolume")
        self.generalvolume.setGeometry(QRect(80, 20, 41, 22))
        self.generalvolume.setDecimals(1)
        self.generalvolume.setMaximum(10.000000000000000)
        self.generalvolume.setSingleStep(0.100000000000000)
        self.generalvolume.setValue(0.500000000000000)
        self.musicvolume = QDoubleSpinBox(self.audio)
        self.musicvolume.setObjectName(u"musicvolume")
        self.musicvolume.setGeometry(QRect(80, 50, 41, 22))
        self.musicvolume.setDecimals(1)
        self.musicvolume.setMaximum(10.000000000000000)
        self.musicvolume.setSingleStep(0.100000000000000)
        self.musicvolume.setValue(0.500000000000000)
        self.samplevolume = QDoubleSpinBox(self.audio)
        self.samplevolume.setObjectName(u"samplevolume")
        self.samplevolume.setGeometry(QRect(80, 80, 41, 22))
        self.samplevolume.setDecimals(1)
        self.samplevolume.setMaximum(10.000000000000000)
        self.samplevolume.setSingleStep(0.100000000000000)
        self.samplevolume.setValue(0.500000000000000)
        self.audiobeatscale = QDoubleSpinBox(self.audio)
        self.audiobeatscale.setObjectName(u"audiobeatscale")
        self.audiobeatscale.setGeometry(QRect(80, 140, 41, 22))
        self.audiobeatscale.setDecimals(1)
        self.audiobeatscale.setMaximum(10.000000000000000)
        self.audiobeatscale.setSingleStep(0.100000000000000)
        self.audiobeatscale.setValue(1.200000000000000)
        self.label_16 = QLabel(self.audio)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 20, 61, 21))
        self.label_17 = QLabel(self.audio)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 50, 61, 21))
        self.label_18 = QLabel(self.audio)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 80, 61, 21))
        self.label_19 = QLabel(self.audio)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 110, 61, 21))
        self.label_20 = QLabel(self.audio)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 140, 61, 21))
        self.label_35 = QLabel(self.audio)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 170, 101, 21))
        self.positionmultiplier = QDoubleSpinBox(self.audio)
        self.positionmultiplier.setObjectName(u"positionmultiplier")
        self.positionmultiplier.setGeometry(QRect(110, 170, 41, 22))
        self.positionmultiplier.setDecimals(1)
        self.positionmultiplier.setMaximum(5.000000000000000)
        self.positionmultiplier.setSingleStep(0.100000000000000)
        self.positionmultiplier.setValue(1.000000000000000)
        self.ignoresamples = QCheckBox(self.audio)
        self.ignoresamples.setObjectName(u"ignoresamples")
        self.ignoresamples.setGeometry(QRect(10, 200, 151, 20))
        self.ignoresamplevolume = QCheckBox(self.audio)
        self.ignoresamplevolume.setObjectName(u"ignoresamplevolume")
        self.ignoresamplevolume.setGeometry(QRect(10, 220, 191, 20))
        self.usingtimingpoints = QCheckBox(self.audio)
        self.usingtimingpoints.setObjectName(u"usingtimingpoints")
        self.usingtimingpoints.setGeometry(QRect(10, 240, 191, 20))
        self.offset = QSpinBox(self.audio)
        self.offset.setObjectName(u"offset")
        self.offset.setGeometry(QRect(80, 110, 42, 22))
        self.skins = QLineEdit(Dialog)
        self.skins.setObjectName(u"skins")
        self.skins.setGeometry(QRect(50, 240, 281, 22))
        self.songs = QLineEdit(Dialog)
        self.songs.setObjectName(u"songs")
        self.songs.setGeometry(QRect(50, 210, 281, 22))
        self.label_21 = QLabel(Dialog)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 210, 41, 20))
        self.label_22 = QLabel(Dialog)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 240, 31, 20))
        self.label_23 = QLabel(Dialog)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(0, 0, 271, 16))
        self.label_23.setStyleSheet(u"color: red;")
        self.label_23.setAlignment(Qt.AlignCenter)
        self.label_23.setMargin(1)
        self.label_23.setOpenExternalLinks(False)
        self.label_24 = QLabel(Dialog)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 190, 281, 16))
        self.label_24.setStyleSheet(u"color: red;")
        self.label_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_24.setMargin(1)
        self.label_24.setOpenExternalLinks(False)
        self.sking = QGroupBox(Dialog)
        self.sking.setObjectName(u"sking")
        self.sking.setGeometry(QRect(340, 0, 161, 271))
        self.skin = QLineEdit(self.sking)
        self.skin.setObjectName(u"skin")
        self.skin.setGeometry(QRect(40, 20, 113, 22))
        self.label_30 = QLabel(self.sking)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 20, 31, 21))
        self.colorsfromskin = QCheckBox(self.sking)
        self.colorsfromskin.setObjectName(u"colorsfromskin")
        self.colorsfromskin.setGeometry(QRect(10, 50, 111, 20))
        self.beatmapcolors = QCheckBox(self.sking)
        self.beatmapcolors.setObjectName(u"beatmapcolors")
        self.beatmapcolors.setGeometry(QRect(10, 70, 111, 20))
        self.skincursor = QCheckBox(self.sking)
        self.skincursor.setObjectName(u"skincursor")
        self.skincursor.setGeometry(QRect(10, 90, 111, 20))
        self.cursorscale = QDoubleSpinBox(self.sking)
        self.cursorscale.setObjectName(u"cursorscale")
        self.cursorscale.setGeometry(QRect(60, 110, 62, 22))
        self.cursorscale.setMaximum(5.000000000000000)
        self.cursorscale.setSingleStep(0.100000000000000)
        self.cursorscale.setValue(1.000000000000000)
        self.label_34 = QLabel(self.sking)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 110, 49, 21))
        self.label_31 = QLabel(Dialog)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 160, 101, 21))
        self.playername = QLineEdit(Dialog)
        self.playername.setObjectName(u"playername")
        self.playername.setGeometry(QRect(120, 160, 151, 22))
        self.timing = QGroupBox(Dialog)
        self.timing.setObjectName(u"timing")
        self.timing.setGeometry(QRect(190, 590, 141, 81))
        self.starts = QDoubleSpinBox(self.timing)
        self.starts.setObjectName(u"starts")
        self.starts.setGeometry(QRect(61, 20, 71, 22))
        self.starts.setDecimals(1)
        self.starts.setMaximum(9999999.000000000000000)
        self.starts.setSingleStep(0.100000000000000)
        self.ends = QDoubleSpinBox(self.timing)
        self.ends.setObjectName(u"ends")
        self.ends.setGeometry(QRect(61, 50, 71, 22))
        self.ends.setDecimals(1)
        self.ends.setMaximum(99999999.000000000000000)
        self.ends.setSingleStep(0.100000000000000)
        self.start = QCheckBox(self.timing)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(10, 20, 75, 20))
        self.end = QCheckBox(self.timing)
        self.end.setObjectName(u"end")
        self.end.setGeometry(QRect(10, 50, 75, 20))
        self.lineEdit = QLineEdit(Dialog)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(190, 730, 511, 22))
        self.overlay = QTabWidget(Dialog)
        self.overlay.setObjectName(u"overlay")
        self.overlay.setGeometry(QRect(0, 410, 701, 141))
        self.overlay.setTabBarAutoHide(False)
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.hiterrormeter = QCheckBox(self.tab_8)
        self.hiterrormeter.setObjectName(u"hiterrormeter")
        self.hiterrormeter.setGeometry(QRect(10, 10, 111, 20))
        self.hiterrormeter.setChecked(True)
        self.other_8 = QGroupBox(self.tab_8)
        self.other_8.setObjectName(u"other_8")
        self.other_8.setGeometry(QRect(560, 0, 131, 111))
        self.label_70 = QLabel(self.other_8)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(10, 50, 49, 21))
        self.label_71 = QLabel(self.other_8)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(10, 20, 31, 21))
        self.hiterrormeteropacity = QDoubleSpinBox(self.other_8)
        self.hiterrormeteropacity.setObjectName(u"hiterrormeteropacity")
        self.hiterrormeteropacity.setGeometry(QRect(60, 50, 62, 22))
        self.hiterrormeteropacity.setMaximum(1.000000000000000)
        self.hiterrormeteropacity.setSingleStep(0.100000000000000)
        self.hiterrormeteropacity.setValue(1.000000000000000)
        self.hiterrormeterscale = QSpinBox(self.other_8)
        self.hiterrormeterscale.setObjectName(u"hiterrormeterscale")
        self.hiterrormeterscale.setGeometry(QRect(60, 20, 61, 22))
        self.hiterrormeterscale.setMinimum(1)
        self.hiterrormeterscale.setMaximum(5)
        self.overlay.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.score = QCheckBox(self.tab_9)
        self.score.setObjectName(u"score")
        self.score.setGeometry(QRect(10, 10, 51, 20))
        self.score.setChecked(True)
        self.other_7 = QGroupBox(self.tab_9)
        self.other_7.setObjectName(u"other_7")
        self.other_7.setGeometry(QRect(560, 0, 131, 111))
        self.label_68 = QLabel(self.other_7)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(10, 50, 49, 21))
        self.label_69 = QLabel(self.other_7)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(10, 20, 31, 21))
        self.scoreopacity = QDoubleSpinBox(self.other_7)
        self.scoreopacity.setObjectName(u"scoreopacity")
        self.scoreopacity.setGeometry(QRect(60, 50, 62, 22))
        self.scoreopacity.setMaximum(1.000000000000000)
        self.scoreopacity.setSingleStep(0.100000000000000)
        self.scoreopacity.setValue(1.000000000000000)
        self.scorescale = QSpinBox(self.other_7)
        self.scorescale.setObjectName(u"scorescale")
        self.scorescale.setGeometry(QRect(60, 20, 61, 22))
        self.scorescale.setMinimum(1)
        self.scorescale.setMaximum(5)
        self.overlay.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.hpbar = QCheckBox(self.tab_10)
        self.hpbar.setObjectName(u"hpbar")
        self.hpbar.setGeometry(QRect(10, 10, 61, 20))
        self.hpbar.setChecked(True)
        self.groupBox_4 = QGroupBox(self.tab_10)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(560, 0, 131, 111))
        self.label_41 = QLabel(self.groupBox_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 50, 49, 21))
        self.label_40 = QLabel(self.groupBox_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 20, 31, 21))
        self.hpbaropacity = QDoubleSpinBox(self.groupBox_4)
        self.hpbaropacity.setObjectName(u"hpbaropacity")
        self.hpbaropacity.setGeometry(QRect(60, 50, 62, 22))
        self.hpbaropacity.setMaximum(1.000000000000000)
        self.hpbaropacity.setSingleStep(0.100000000000000)
        self.hpbaropacity.setValue(1.000000000000000)
        self.hpbarscale = QSpinBox(self.groupBox_4)
        self.hpbarscale.setObjectName(u"hpbarscale")
        self.hpbarscale.setGeometry(QRect(60, 20, 61, 22))
        self.hpbarscale.setMinimum(1)
        self.hpbarscale.setMaximum(5)
        self.overlay.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.combocounter = QCheckBox(self.tab_11)
        self.combocounter.setObjectName(u"combocounter")
        self.combocounter.setGeometry(QRect(10, 10, 111, 20))
        self.combocounter.setChecked(True)
        self.other_6 = QGroupBox(self.tab_11)
        self.other_6.setObjectName(u"other_6")
        self.other_6.setGeometry(QRect(560, 0, 131, 111))
        self.label_66 = QLabel(self.other_6)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(10, 50, 49, 21))
        self.label_67 = QLabel(self.other_6)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(10, 20, 31, 21))
        self.combocounteropacity = QDoubleSpinBox(self.other_6)
        self.combocounteropacity.setObjectName(u"combocounteropacity")
        self.combocounteropacity.setGeometry(QRect(60, 50, 62, 22))
        self.combocounteropacity.setMaximum(1.000000000000000)
        self.combocounteropacity.setSingleStep(0.100000000000000)
        self.combocounteropacity.setValue(1.000000000000000)
        self.combocounterscale = QSpinBox(self.other_6)
        self.combocounterscale.setObjectName(u"combocounterscale")
        self.combocounterscale.setGeometry(QRect(60, 20, 61, 22))
        self.combocounterscale.setMinimum(1)
        self.combocounterscale.setMaximum(5)
        self.overlay.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.ppcounter = QCheckBox(self.tab_12)
        self.ppcounter.setObjectName(u"ppcounter")
        self.ppcounter.setGeometry(QRect(10, 10, 81, 20))
        self.ppcounter.setChecked(True)
        self.other_5 = QGroupBox(self.tab_12)
        self.other_5.setObjectName(u"other_5")
        self.other_5.setGeometry(QRect(560, 0, 131, 111))
        self.label_64 = QLabel(self.other_5)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(10, 50, 49, 21))
        self.label_65 = QLabel(self.other_5)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(10, 20, 31, 21))
        self.ppcounteropacity = QDoubleSpinBox(self.other_5)
        self.ppcounteropacity.setObjectName(u"ppcounteropacity")
        self.ppcounteropacity.setGeometry(QRect(60, 50, 62, 22))
        self.ppcounteropacity.setMaximum(1.000000000000000)
        self.ppcounteropacity.setSingleStep(0.100000000000000)
        self.ppcounteropacity.setValue(1.000000000000000)
        self.ppcounterscale = QSpinBox(self.other_5)
        self.ppcounterscale.setObjectName(u"ppcounterscale")
        self.ppcounterscale.setGeometry(QRect(60, 20, 61, 22))
        self.ppcounterscale.setMinimum(1)
        self.ppcounterscale.setMaximum(5)
        self.ppxpos = QSpinBox(self.tab_12)
        self.ppxpos.setObjectName(u"ppxpos")
        self.ppxpos.setGeometry(QRect(50, 30, 121, 22))
        self.ppxpos.setMaximum(1920)
        self.ppxpos.setSingleStep(10)
        self.ppxpos.setValue(5)
        self.label_44 = QLabel(self.tab_12)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 30, 31, 21))
        self.label_45 = QLabel(self.tab_12)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 60, 31, 21))
        self.ppypos = QSpinBox(self.tab_12)
        self.ppypos.setObjectName(u"ppypos")
        self.ppypos.setGeometry(QRect(50, 60, 121, 21))
        self.ppypos.setMaximum(1080)
        self.ppypos.setSingleStep(10)
        self.ppypos.setValue(150)
        self.label_50 = QLabel(self.tab_12)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(180, 10, 31, 21))
        self.ppalign = QComboBox(self.tab_12)
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.addItem("")
        self.ppalign.setObjectName(u"ppalign")
        self.ppalign.setGeometry(QRect(220, 10, 81, 22))
        self.ppalign.setEditable(False)
        self.overlay.addTab(self.tab_12, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.keyoverlay = QCheckBox(self.tab_13)
        self.keyoverlay.setObjectName(u"keyoverlay")
        self.keyoverlay.setGeometry(QRect(10, 10, 81, 20))
        self.keyoverlay.setChecked(True)
        self.other = QGroupBox(self.tab_13)
        self.other.setObjectName(u"other")
        self.other.setGeometry(QRect(560, 0, 131, 111))
        self.label_42 = QLabel(self.other)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 50, 49, 21))
        self.label_43 = QLabel(self.other)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 20, 31, 21))
        self.keyoverlayopacity = QDoubleSpinBox(self.other)
        self.keyoverlayopacity.setObjectName(u"keyoverlayopacity")
        self.keyoverlayopacity.setGeometry(QRect(60, 50, 62, 22))
        self.keyoverlayopacity.setMaximum(1.000000000000000)
        self.keyoverlayopacity.setSingleStep(0.100000000000000)
        self.keyoverlayopacity.setValue(1.000000000000000)
        self.keyoverlayscale = QSpinBox(self.other)
        self.keyoverlayscale.setObjectName(u"keyoverlayscale")
        self.keyoverlayscale.setGeometry(QRect(60, 20, 61, 22))
        self.keyoverlayscale.setMinimum(1)
        self.keyoverlayscale.setMaximum(5)
        self.overlay.addTab(self.tab_13, "")
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.mods = QCheckBox(self.tab_14)
        self.mods.setObjectName(u"mods")
        self.mods.setGeometry(QRect(10, 10, 75, 20))
        self.mods.setChecked(True)
        self.other_4 = QGroupBox(self.tab_14)
        self.other_4.setObjectName(u"other_4")
        self.other_4.setGeometry(QRect(560, 0, 131, 111))
        self.label_62 = QLabel(self.other_4)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(10, 50, 49, 21))
        self.label_63 = QLabel(self.other_4)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(10, 20, 31, 21))
        self.modsopacity = QDoubleSpinBox(self.other_4)
        self.modsopacity.setObjectName(u"modsopacity")
        self.modsopacity.setGeometry(QRect(60, 50, 62, 22))
        self.modsopacity.setMaximum(1.000000000000000)
        self.modsopacity.setSingleStep(0.100000000000000)
        self.modsopacity.setValue(1.000000000000000)
        self.modsscale = QSpinBox(self.other_4)
        self.modsscale.setObjectName(u"modsscale")
        self.modsscale.setGeometry(QRect(60, 20, 61, 22))
        self.modsscale.setMinimum(1)
        self.modsscale.setMaximum(5)
        self.overlay.addTab(self.tab_14, "")
        self.tab_15 = QWidget()
        self.tab_15.setObjectName(u"tab_15")
        self.scoreboard = QCheckBox(self.tab_15)
        self.scoreboard.setObjectName(u"scoreboard")
        self.scoreboard.setGeometry(QRect(10, 10, 81, 20))
        self.scoreboard.setChecked(True)
        self.other_2 = QGroupBox(self.tab_15)
        self.other_2.setObjectName(u"other_2")
        self.other_2.setGeometry(QRect(560, 0, 131, 111))
        self.label_58 = QLabel(self.other_2)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 50, 49, 21))
        self.label_59 = QLabel(self.other_2)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 20, 31, 21))
        self.scoreboardopacity = QDoubleSpinBox(self.other_2)
        self.scoreboardopacity.setObjectName(u"scoreboardopacity")
        self.scoreboardopacity.setGeometry(QRect(60, 50, 62, 22))
        self.scoreboardopacity.setMaximum(1.000000000000000)
        self.scoreboardopacity.setSingleStep(0.100000000000000)
        self.scoreboardopacity.setValue(1.000000000000000)
        self.scoreboardscale = QSpinBox(self.other_2)
        self.scoreboardscale.setObjectName(u"scoreboardscale")
        self.scoreboardscale.setGeometry(QRect(60, 20, 61, 22))
        self.scoreboardscale.setMinimum(1)
        self.scoreboardscale.setMaximum(5)
        self.checkBox = QCheckBox(self.tab_15)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 40, 81, 20))
        self.overlay.addTab(self.tab_15, "")
        self.tab_16 = QWidget()
        self.tab_16.setObjectName(u"tab_16")
        self.boundaries = QCheckBox(self.tab_16)
        self.boundaries.setObjectName(u"boundaries")
        self.boundaries.setGeometry(QRect(10, 10, 81, 20))
        self.boundaries.setChecked(True)
        self.overlay.addTab(self.tab_16, "")
        self.tab_21 = QWidget()
        self.tab_21.setObjectName(u"tab_21")
        self.label_51 = QLabel(self.tab_21)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(180, 10, 31, 21))
        self.hitcounter = QCheckBox(self.tab_21)
        self.hitcounter.setObjectName(u"hitcounter")
        self.hitcounter.setGeometry(QRect(10, 10, 81, 20))
        self.hitcounter.setChecked(True)
        self.hcypos = QSpinBox(self.tab_21)
        self.hcypos.setObjectName(u"hcypos")
        self.hcypos.setGeometry(QRect(50, 60, 121, 21))
        self.hcypos.setMaximum(1080)
        self.hcypos.setSingleStep(10)
        self.hcypos.setValue(190)
        self.label_52 = QLabel(self.tab_21)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 60, 31, 21))
        self.label_53 = QLabel(self.tab_21)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 30, 31, 21))
        self.other_9 = QGroupBox(self.tab_21)
        self.other_9.setObjectName(u"other_9")
        self.other_9.setGeometry(QRect(560, 0, 131, 111))
        self.label_73 = QLabel(self.other_9)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(10, 50, 49, 21))
        self.label_74 = QLabel(self.other_9)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(10, 20, 31, 21))
        self.hcopacity = QDoubleSpinBox(self.other_9)
        self.hcopacity.setObjectName(u"hcopacity")
        self.hcopacity.setGeometry(QRect(60, 50, 62, 22))
        self.hcopacity.setMaximum(1.000000000000000)
        self.hcopacity.setSingleStep(0.100000000000000)
        self.hcopacity.setValue(1.000000000000000)
        self.hcscale = QSpinBox(self.other_9)
        self.hcscale.setObjectName(u"hcscale")
        self.hcscale.setGeometry(QRect(60, 20, 61, 22))
        self.hcscale.setMinimum(1)
        self.hcscale.setMaximum(5)
        self.hcxpos = QSpinBox(self.tab_21)
        self.hcxpos.setObjectName(u"hcxpos")
        self.hcxpos.setGeometry(QRect(50, 30, 121, 22))
        self.hcxpos.setMaximum(1920)
        self.hcxpos.setSingleStep(10)
        self.hcxpos.setValue(5)
        self.hcalign = QComboBox(self.tab_21)
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.addItem("")
        self.hcalign.setObjectName(u"hcalign")
        self.hcalign.setGeometry(QRect(220, 10, 81, 22))
        self.hcalign.setEditable(False)
        self.overlay.addTab(self.tab_21, "")
        self.tab_22 = QWidget()
        self.tab_22.setObjectName(u"tab_22")
        self.other_10 = QGroupBox(self.tab_22)
        self.other_10.setObjectName(u"other_10")
        self.other_10.setGeometry(QRect(560, 0, 131, 111))
        self.label_75 = QLabel(self.other_10)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(10, 50, 49, 21))
        self.label_76 = QLabel(self.other_10)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(10, 20, 31, 21))
        self.aemopacity = QDoubleSpinBox(self.other_10)
        self.aemopacity.setObjectName(u"aemopacity")
        self.aemopacity.setGeometry(QRect(60, 50, 62, 22))
        self.aemopacity.setMaximum(1.000000000000000)
        self.aemopacity.setSingleStep(0.100000000000000)
        self.aemopacity.setValue(1.000000000000000)
        self.aemscale = QSpinBox(self.other_10)
        self.aemscale.setObjectName(u"aemscale")
        self.aemscale.setGeometry(QRect(60, 20, 61, 22))
        self.aemscale.setMinimum(1)
        self.aemscale.setMaximum(5)
        self.aem = QCheckBox(self.tab_22)
        self.aem.setObjectName(u"aem")
        self.aem.setGeometry(QRect(10, 10, 111, 20))
        self.aem.setChecked(False)
        self.aemxpos = QSpinBox(self.tab_22)
        self.aemxpos.setObjectName(u"aemxpos")
        self.aemxpos.setGeometry(QRect(50, 30, 121, 22))
        self.aemxpos.setMaximum(1920)
        self.aemxpos.setSingleStep(10)
        self.aemxpos.setValue(5)
        self.label_54 = QLabel(self.tab_22)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(180, 10, 31, 21))
        self.label_55 = QLabel(self.tab_22)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(10, 60, 31, 21))
        self.label_56 = QLabel(self.tab_22)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(10, 30, 31, 21))
        self.aemalign = QComboBox(self.tab_22)
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.addItem("")
        self.aemalign.setObjectName(u"aemalign")
        self.aemalign.setGeometry(QRect(220, 10, 81, 22))
        self.aemalign.setEditable(False)
        self.aemypos = QSpinBox(self.tab_22)
        self.aemypos.setObjectName(u"aemypos")
        self.aemypos.setGeometry(QRect(50, 60, 121, 21))
        self.aemypos.setMaximum(1080)
        self.aemypos.setSingleStep(10)
        self.aemypos.setValue(190)
        self.overlay.addTab(self.tab_22, "")
        self.knockoutmode = QGroupBox(Dialog)
        self.knockoutmode.setObjectName(u"knockoutmode")
        self.knockoutmode.setGeometry(QRect(10, 590, 171, 191))
        self.knockout = QCheckBox(self.knockoutmode)
        self.knockout.setObjectName(u"knockout")
        self.knockout.setGeometry(QRect(10, 20, 111, 20))
        self.modlist = QGroupBox(self.knockoutmode)
        self.modlist.setObjectName(u"modlist")
        self.modlist.setGeometry(QRect(10, 40, 151, 141))
        self.gridLayoutWidget = QWidget(self.modlist)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 20, 131, 111))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.hdfi = QCheckBox(self.gridLayoutWidget)
        self.hdfi.setObjectName(u"hdfi")
        self.hdfi.setChecked(False)
        self.hdfi.setTristate(True)

        self.gridLayout.addWidget(self.hdfi, 1, 0, 1, 1)

        self.dtnc = QCheckBox(self.gridLayoutWidget)
        self.dtnc.setObjectName(u"dtnc")
        self.dtnc.setChecked(False)
        self.dtnc.setTristate(True)

        self.gridLayout.addWidget(self.dtnc, 2, 0, 1, 1)

        self.sdpf = QCheckBox(self.gridLayoutWidget)
        self.sdpf.setObjectName(u"sdpf")
        self.sdpf.setChecked(False)
        self.sdpf.setTristate(True)

        self.gridLayout.addWidget(self.sdpf, 0, 0, 1, 1)

        self.ht = QCheckBox(self.gridLayoutWidget)
        self.ht.setObjectName(u"ht")
        self.ht.setChecked(False)
        self.ht.setTristate(False)

        self.gridLayout.addWidget(self.ht, 2, 1, 1, 1)

        self.nf = QCheckBox(self.gridLayoutWidget)
        self.nf.setObjectName(u"nf")
        self.nf.setChecked(False)
        self.nf.setTristate(False)

        self.gridLayout.addWidget(self.nf, 0, 1, 1, 1)

        self.fl = QCheckBox(self.gridLayoutWidget)
        self.fl.setObjectName(u"fl")
        self.fl.setChecked(False)
        self.fl.setTristate(False)

        self.gridLayout.addWidget(self.fl, 1, 1, 1, 1)

        self.ezhr = QCheckBox(self.gridLayoutWidget)
        self.ezhr.setObjectName(u"ezhr")
        self.ezhr.setChecked(False)
        self.ezhr.setTristate(True)

        self.gridLayout.addWidget(self.ezhr, 3, 0, 1, 1)

        self.logo = QLabel(Dialog)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(280, 150, 51, 51))
        self.logo.setPixmap(QPixmap(u"../0.6.3/icon.png"))
        self.logo.setScaledContents(True)
        self.textEdit = QTextEdit(Dialog)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QRect(10, 20, 321, 111))
        self.textEdit.setReadOnly(True)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(340, 590, 351, 131))
        self.title = QCheckBox(self.groupBox_3)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(10, 20, 61, 16))
        self.author = QCheckBox(self.groupBox_3)
        self.author.setObjectName(u"author")
        self.author.setGeometry(QRect(10, 40, 61, 16))
        self.creator = QCheckBox(self.groupBox_3)
        self.creator.setObjectName(u"creator")
        self.creator.setGeometry(QRect(10, 60, 61, 16))
        self.titlec = QLineEdit(self.groupBox_3)
        self.titlec.setObjectName(u"titlec")
        self.titlec.setGeometry(QRect(80, 20, 113, 16))
        self.authorc = QLineEdit(self.groupBox_3)
        self.authorc.setObjectName(u"authorc")
        self.authorc.setGeometry(QRect(80, 40, 113, 16))
        self.creatorc = QLineEdit(self.groupBox_3)
        self.creatorc.setObjectName(u"creatorc")
        self.creatorc.setGeometry(QRect(80, 60, 113, 16))
        self.difficulty = QCheckBox(self.groupBox_3)
        self.difficulty.setObjectName(u"difficulty")
        self.difficulty.setGeometry(QRect(200, 20, 71, 16))
        self.difficultyc = QLineEdit(self.groupBox_3)
        self.difficultyc.setObjectName(u"difficultyc")
        self.difficultyc.setGeometry(QRect(200, 40, 113, 16))
        self.skip = QCheckBox(self.groupBox_3)
        self.skip.setObjectName(u"skip")
        self.skip.setGeometry(QRect(200, 60, 51, 20))
        self.qstart = QCheckBox(self.groupBox_3)
        self.qstart.setObjectName(u"qstart")
        self.qstart.setGeometry(QRect(250, 60, 81, 20))
        self.tag = QCheckBox(self.groupBox_3)
        self.tag.setObjectName(u"tag")
        self.tag.setGeometry(QRect(10, 80, 61, 16))
        self.tagc = QSpinBox(self.groupBox_3)
        self.tagc.setObjectName(u"tagc")
        self.tagc.setGeometry(QRect(80, 80, 42, 22))
        self.cursors = QCheckBox(self.groupBox_3)
        self.cursors.setObjectName(u"cursors")
        self.cursors.setGeometry(QRect(10, 100, 61, 16))
        self.cursorsc = QSpinBox(self.groupBox_3)
        self.cursorsc.setObjectName(u"cursorsc")
        self.cursorsc.setGeometry(QRect(80, 100, 42, 22))

        self.retranslateUi(Dialog)

        self.settings.setCurrentIndex(3)
        self.overlay.setCurrentIndex(9)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
#if QT_CONFIG(tooltip)
        self.settings.setToolTip(QCoreApplication.translate("Dialog", u"graphics", None))
#endif // QT_CONFIG(tooltip)
        self.vsync.setText(QCoreApplication.translate("Dialog", u"VSync", None))
        self.fullscreenbutton.setText(QCoreApplication.translate("Dialog", u"Fullscreen", None))
        self.showfps.setText(QCoreApplication.translate("Dialog", u"Show FPS", None))
        self.label_36.setText(QCoreApplication.translate("Dialog", u"FPS cap", None))
        self.label_37.setText(QCoreApplication.translate("Dialog", u"MSAA", None))
        self.usepersistentbuffers.setText(QCoreApplication.translate("Dialog", u"Use persistent buffers", None))
        self.label_46.setText(QCoreApplication.translate("Dialog", u"Height", None))
        self.label_47.setText(QCoreApplication.translate("Dialog", u"Width", None))
        self.label_48.setText(QCoreApplication.translate("Dialog", u"Window height", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"Window width", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_18), QCoreApplication.translate("Dialog", u"Graphics", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Colors", None))
        self.enablerainbow.setText(QCoreApplication.translate("Dialog", u"Rainbow", None))
        self.label_32.setText(QCoreApplication.translate("Dialog", u"Trail Style", None))
        self.label_33.setText(QCoreApplication.translate("Dialog", u"Style23speed", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_17), QCoreApplication.translate("Dialog", u"Cursor", None))
        self.resultscreen.setText(QCoreApplication.translate("Dialog", u"Result screen", None))
        self.label_38.setText(QCoreApplication.translate("Dialog", u"Result screen time", None))
        self.label_39.setText(QCoreApplication.translate("Dialog", u"Flash light dim", None))
        self.warningerrors.setText(QCoreApplication.translate("Dialog", u"Warning arrows", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_19), QCoreApplication.translate("Dialog", u"Gameplay", None))
        self.xkey.setKeySequence(QCoreApplication.translate("Dialog", u"Z", None))
        self.zkey.setKeySequence(QCoreApplication.translate("Dialog", u"X", None))
        self.rkey.setKeySequence(QCoreApplication.translate("Dialog", u"`", None))
        self.ckey.setKeySequence(QCoreApplication.translate("Dialog", u"C", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Left", None))
        self.label_26.setText(QCoreApplication.translate("Dialog", u"Right", None))
        self.label_27.setText(QCoreApplication.translate("Dialog", u"Reset", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Smoke", None))
        self.mouse.setText(QCoreApplication.translate("Dialog", u"Mouse buttons", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"Mouse sensivity", None))
        self.mousehighprecision.setText(QCoreApplication.translate("Dialog", u"Mouse high precision", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_7), QCoreApplication.translate("Dialog", u"Input", None))
        self.loadstoryboards.setText(QCoreApplication.translate("Dialog", u"Load storyboards", None))
        self.loadvideos.setText(QCoreApplication.translate("Dialog", u"Load videos", None))
        self.flashtobeat.setText(QCoreApplication.translate("Dialog", u"Flash to beat", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"Background", None))
        self.bloom.setText(QCoreApplication.translate("Dialog", u"Bloom", None))
        self.bloomtobeat.setText(QCoreApplication.translate("Dialog", u"Bloom to beat", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Power", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Blur", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Threshold", None))
        self.settings.setTabText(self.settings.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Bloom", None))
        self.blur.setText(QCoreApplication.translate("Dialog", u"Blur", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Animation", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Normal", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Intro", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Breaks", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Blur", None))
        self.dimanim.setTitle(QCoreApplication.translate("Dialog", u"Animation", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Normal", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Intro", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Breaks", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"Dim", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Speed", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Amount", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_5), QCoreApplication.translate("Dialog", u"Paralax", None))
        self.triangles.setText(QCoreApplication.translate("Dialog", u"Triangles", None))
        self.trianglesshadow.setText(QCoreApplication.translate("Dialog", u"Shadowed", None))
        self.trianglesdrawoverblur.setText(QCoreApplication.translate("Dialog", u"Draw over blur", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Paralax multiplier", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"Density", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.label_15.setText(QCoreApplication.translate("Dialog", u"Speed", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_6), QCoreApplication.translate("Dialog", u"Triangles", None))
        self.drawspectrum.setText(QCoreApplication.translate("Dialog", u"Logo", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Dialog", u"Animation", None))
        self.label_60.setText(QCoreApplication.translate("Dialog", u"Normal", None))
        self.label_61.setText(QCoreApplication.translate("Dialog", u"Intro", None))
        self.label_72.setText(QCoreApplication.translate("Dialog", u"Breaks", None))
        self.settings.setTabText(self.settings.indexOf(self.tab_20), QCoreApplication.translate("Dialog", u"Logo", None))
#if QT_CONFIG(tooltip)
        self.coinfirm.setToolTip(QCoreApplication.translate("Dialog", u"coinfirm your settings", None))
#endif // QT_CONFIG(tooltip)
        self.coinfirm.setText(QCoreApplication.translate("Dialog", u"Coinfirm", None))
#if QT_CONFIG(tooltip)
        self.exit.setToolTip(QCoreApplication.translate("Dialog", u"close app", None))
#endif // QT_CONFIG(tooltip)
        self.exit.setText(QCoreApplication.translate("Dialog", u"Open", None))
#if QT_CONFIG(tooltip)
        self.play.setToolTip(QCoreApplication.translate("Dialog", u"launch danser", None))
#endif // QT_CONFIG(tooltip)
        self.play.setText(QCoreApplication.translate("Dialog", u"Play", None))
        self.audio.setTitle(QCoreApplication.translate("Dialog", u"Audio", None))
#if QT_CONFIG(tooltip)
        self.generalvolume.setToolTip(QCoreApplication.translate("Dialog", u"general volume", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.musicvolume.setToolTip(QCoreApplication.translate("Dialog", u"music volume", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.samplevolume.setToolTip(QCoreApplication.translate("Dialog", u"sample volume", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.audiobeatscale.setToolTip(QCoreApplication.translate("Dialog", u"beatscale", None))
#endif // QT_CONFIG(tooltip)
        self.label_16.setText(QCoreApplication.translate("Dialog", u"General", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"Music", None))
        self.label_18.setText(QCoreApplication.translate("Dialog", u"Sample", None))
        self.label_19.setText(QCoreApplication.translate("Dialog", u"Offset", None))
        self.label_20.setText(QCoreApplication.translate("Dialog", u"Beatscale", None))
        self.label_35.setText(QCoreApplication.translate("Dialog", u"position multiplier", None))
#if QT_CONFIG(tooltip)
        self.positionmultiplier.setToolTip(QCoreApplication.translate("Dialog", u"beatscale", None))
#endif // QT_CONFIG(tooltip)
        self.ignoresamples.setText(QCoreApplication.translate("Dialog", u"Ignore beatmap samples", None))
        self.ignoresamplevolume.setText(QCoreApplication.translate("Dialog", u"Ignore beatmap samplevolume", None))
        self.usingtimingpoints.setText(QCoreApplication.translate("Dialog", u"Beatmap using timing points", None))
#if QT_CONFIG(tooltip)
        self.skins.setToolTip(QCoreApplication.translate("Dialog", u"skins folder", None))
#endif // QT_CONFIG(tooltip)
        self.skins.setText(QCoreApplication.translate("Dialog", u"C:\\\\Users\\\\USER\\\\AppData\\\\Local\\\\osu!\\\\Skins", None))
        self.skins.setPlaceholderText("")
#if QT_CONFIG(tooltip)
        self.songs.setToolTip(QCoreApplication.translate("Dialog", u"songs folder", None))
#endif // QT_CONFIG(tooltip)
        self.songs.setInputMask("")
        self.songs.setText(QCoreApplication.translate("Dialog", u"C:\\\\Users\\\\USER\\\\AppData\\\\Local\\\\osu!\\\\Songs", None))
        self.songs.setPlaceholderText("")
        self.label_21.setText(QCoreApplication.translate("Dialog", u"Songs:", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"Skins", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Make a copy of the settings.json file in advance!!!", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Instead of \"\\\" use \"\\\\\". Example: C:\\\\users\\\\songs", None))
        self.sking.setTitle(QCoreApplication.translate("Dialog", u"Skin", None))
#if QT_CONFIG(tooltip)
        self.skin.setToolTip(QCoreApplication.translate("Dialog", u"skin name", None))
#endif // QT_CONFIG(tooltip)
        self.skin.setText(QCoreApplication.translate("Dialog", u"default", None))
        self.label_30.setText(QCoreApplication.translate("Dialog", u"Skin:", None))
        self.colorsfromskin.setText(QCoreApplication.translate("Dialog", u"Colors from skin", None))
        self.beatmapcolors.setText(QCoreApplication.translate("Dialog", u"Beatmap colors", None))
        self.skincursor.setText(QCoreApplication.translate("Dialog", u"Skin cursor", None))
        self.label_34.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Player username:", None))
#if QT_CONFIG(tooltip)
        self.playername.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.playername.setText(QCoreApplication.translate("Dialog", u"danser", None))
        self.timing.setTitle(QCoreApplication.translate("Dialog", u"Timing", None))
#if QT_CONFIG(tooltip)
        self.starts.setToolTip(QCoreApplication.translate("Dialog", u"Start at the given time in seconds", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.ends.setToolTip(QCoreApplication.translate("Dialog", u"End at the given time in seconds (default +Inf)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.start.setToolTip(QCoreApplication.translate("Dialog", u"Start at the given time in seconds", None))
#endif // QT_CONFIG(tooltip)
        self.start.setText(QCoreApplication.translate("Dialog", u"Start", None))
#if QT_CONFIG(tooltip)
        self.end.setToolTip(QCoreApplication.translate("Dialog", u"End at the given time in seconds (default +Inf)", None))
#endif // QT_CONFIG(tooltip)
        self.end.setText(QCoreApplication.translate("Dialog", u"End", None))
#if QT_CONFIG(tooltip)
        self.lineEdit.setToolTip(QCoreApplication.translate("Dialog", u"launch properties", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.overlay.setToolTip(QCoreApplication.translate("Dialog", u"interface", None))
#endif // QT_CONFIG(tooltip)
        self.hiterrormeter.setText(QCoreApplication.translate("Dialog", u"HitErrorMeter", None))
        self.other_8.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_70.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_71.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_8), QCoreApplication.translate("Dialog", u"HitErrorMeter", None))
        self.score.setText(QCoreApplication.translate("Dialog", u"Score", None))
        self.other_7.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_68.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_69.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_9), QCoreApplication.translate("Dialog", u"Score", None))
        self.hpbar.setText(QCoreApplication.translate("Dialog", u"HPBar", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_41.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_40.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_10), QCoreApplication.translate("Dialog", u"HPBar", None))
        self.combocounter.setText(QCoreApplication.translate("Dialog", u"ComboCounter", None))
        self.other_6.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_66.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_11), QCoreApplication.translate("Dialog", u"ComboCounter", None))
        self.ppcounter.setText(QCoreApplication.translate("Dialog", u"PPCounter", None))
        self.other_5.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_64.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_65.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.label_44.setText(QCoreApplication.translate("Dialog", u"Xpos", None))
        self.label_45.setText(QCoreApplication.translate("Dialog", u"Ypos", None))
        self.label_50.setText(QCoreApplication.translate("Dialog", u"Align", None))
        self.ppalign.setItemText(0, QCoreApplication.translate("Dialog", u"Left", None))
        self.ppalign.setItemText(1, QCoreApplication.translate("Dialog", u"Right", None))
        self.ppalign.setItemText(2, QCoreApplication.translate("Dialog", u"Center", None))
        self.ppalign.setItemText(3, QCoreApplication.translate("Dialog", u"Up", None))
        self.ppalign.setItemText(4, QCoreApplication.translate("Dialog", u"Down", None))
        self.ppalign.setItemText(5, QCoreApplication.translate("Dialog", u"UpLeft", None))
        self.ppalign.setItemText(6, QCoreApplication.translate("Dialog", u"DownLeft", None))
        self.ppalign.setItemText(7, QCoreApplication.translate("Dialog", u"UpRight", None))
        self.ppalign.setItemText(8, QCoreApplication.translate("Dialog", u"DownRight", None))

        self.overlay.setTabText(self.overlay.indexOf(self.tab_12), QCoreApplication.translate("Dialog", u"PPCounter", None))
        self.keyoverlay.setText(QCoreApplication.translate("Dialog", u"KeyOverlay", None))
        self.other.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_42.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_43.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_13), QCoreApplication.translate("Dialog", u"KeyOverlay", None))
        self.mods.setText(QCoreApplication.translate("Dialog", u"Mods", None))
        self.other_4.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_62.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_63.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_14), QCoreApplication.translate("Dialog", u"Mods", None))
        self.scoreboard.setText(QCoreApplication.translate("Dialog", u"ScoreBoard", None))
        self.other_2.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_58.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_59.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.checkBox.setText(QCoreApplication.translate("Dialog", u"Align Right", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_15), QCoreApplication.translate("Dialog", u"ScoreBoard", None))
        self.boundaries.setText(QCoreApplication.translate("Dialog", u"Boundaries", None))
        self.overlay.setTabText(self.overlay.indexOf(self.tab_16), QCoreApplication.translate("Dialog", u"Boundaries", None))
        self.label_51.setText(QCoreApplication.translate("Dialog", u"Align", None))
        self.hitcounter.setText(QCoreApplication.translate("Dialog", u"Hitcounter", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"Ypos", None))
        self.label_53.setText(QCoreApplication.translate("Dialog", u"Xpos", None))
        self.other_9.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_73.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_74.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.hcalign.setItemText(0, QCoreApplication.translate("Dialog", u"Left", None))
        self.hcalign.setItemText(1, QCoreApplication.translate("Dialog", u"Right", None))
        self.hcalign.setItemText(2, QCoreApplication.translate("Dialog", u"Center", None))
        self.hcalign.setItemText(3, QCoreApplication.translate("Dialog", u"Up", None))
        self.hcalign.setItemText(4, QCoreApplication.translate("Dialog", u"Down", None))
        self.hcalign.setItemText(5, QCoreApplication.translate("Dialog", u"UpLeft", None))
        self.hcalign.setItemText(6, QCoreApplication.translate("Dialog", u"DownLeft", None))
        self.hcalign.setItemText(7, QCoreApplication.translate("Dialog", u"UpRight", None))
        self.hcalign.setItemText(8, QCoreApplication.translate("Dialog", u"DownRight", None))

        self.overlay.setTabText(self.overlay.indexOf(self.tab_21), QCoreApplication.translate("Dialog", u"HitCounter", None))
        self.other_10.setTitle(QCoreApplication.translate("Dialog", u"Other", None))
        self.label_75.setText(QCoreApplication.translate("Dialog", u"Opacity", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"Scale", None))
        self.aem.setText(QCoreApplication.translate("Dialog", u"AimErrorMeter", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"Align", None))
        self.label_55.setText(QCoreApplication.translate("Dialog", u"Ypos", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"Xpos", None))
        self.aemalign.setItemText(0, QCoreApplication.translate("Dialog", u"Left", None))
        self.aemalign.setItemText(1, QCoreApplication.translate("Dialog", u"Right", None))
        self.aemalign.setItemText(2, QCoreApplication.translate("Dialog", u"Center", None))
        self.aemalign.setItemText(3, QCoreApplication.translate("Dialog", u"Up", None))
        self.aemalign.setItemText(4, QCoreApplication.translate("Dialog", u"Down", None))
        self.aemalign.setItemText(5, QCoreApplication.translate("Dialog", u"UpLeft", None))
        self.aemalign.setItemText(6, QCoreApplication.translate("Dialog", u"DownLeft", None))
        self.aemalign.setItemText(7, QCoreApplication.translate("Dialog", u"UpRight", None))
        self.aemalign.setItemText(8, QCoreApplication.translate("Dialog", u"DownRight", None))

        self.overlay.setTabText(self.overlay.indexOf(self.tab_22), QCoreApplication.translate("Dialog", u"AimErrorMeter", None))
        self.knockoutmode.setTitle(QCoreApplication.translate("Dialog", u"Knockout mode", None))
        self.knockout.setText(QCoreApplication.translate("Dialog", u"Knockout mode", None))
        self.modlist.setTitle(QCoreApplication.translate("Dialog", u"Mods", None))
#if QT_CONFIG(tooltip)
        self.hdfi.setToolTip(QCoreApplication.translate("Dialog", u"hidden/ fade in", None))
#endif // QT_CONFIG(tooltip)
        self.hdfi.setText(QCoreApplication.translate("Dialog", u"HD/FI", None))
#if QT_CONFIG(tooltip)
        self.dtnc.setToolTip(QCoreApplication.translate("Dialog", u"double time/nightcore", None))
#endif // QT_CONFIG(tooltip)
        self.dtnc.setText(QCoreApplication.translate("Dialog", u"DT/NC", None))
#if QT_CONFIG(tooltip)
        self.sdpf.setToolTip(QCoreApplication.translate("Dialog", u"sudden death/perfect", None))
#endif // QT_CONFIG(tooltip)
        self.sdpf.setText(QCoreApplication.translate("Dialog", u"SD/PF", None))
#if QT_CONFIG(tooltip)
        self.ht.setToolTip(QCoreApplication.translate("Dialog", u"half time", None))
#endif // QT_CONFIG(tooltip)
        self.ht.setText(QCoreApplication.translate("Dialog", u"HT", None))
#if QT_CONFIG(tooltip)
        self.nf.setToolTip(QCoreApplication.translate("Dialog", u"no fail", None))
#endif // QT_CONFIG(tooltip)
        self.nf.setText(QCoreApplication.translate("Dialog", u"NF", None))
#if QT_CONFIG(tooltip)
        self.fl.setToolTip(QCoreApplication.translate("Dialog", u"flash light", None))
#endif // QT_CONFIG(tooltip)
        self.fl.setText(QCoreApplication.translate("Dialog", u"FL", None))
#if QT_CONFIG(tooltip)
        self.ezhr.setToolTip(QCoreApplication.translate("Dialog", u"easy/hard rock", None))
#endif // QT_CONFIG(tooltip)
        self.ezhr.setText(QCoreApplication.translate("Dialog", u"EZ/HR", None))
        self.logo.setText("")
        self.textEdit.setHtml(QCoreApplication.translate("Dialog", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Danser configurator</span> - programm for easy editing <span style=\" font-style:italic;\">settings </span>file. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; m"
                        "argin-right:0px; -qt-block-indent:0; text-indent:0px;\">Made by <a href=\"https://github.com/timofey260\"><span style=\" text-decoration: underline; color:#0000ff;\">timofey260</span></a>  2021</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">danser configurator for <a href=\"https://github.com/Wieku/danser-go\"><span style=\" text-decoration: underline; color:#0000ff;\">danser</span></a> 0.6.4</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Dialog", u"launch", None))
        self.title.setText(QCoreApplication.translate("Dialog", u"Title", None))
        self.author.setText(QCoreApplication.translate("Dialog", u"Artist", None))
        self.creator.setText(QCoreApplication.translate("Dialog", u"Creator", None))
        self.difficulty.setText(QCoreApplication.translate("Dialog", u"Difficulty", None))
        self.skip.setText(QCoreApplication.translate("Dialog", u"Skip", None))
        self.qstart.setText(QCoreApplication.translate("Dialog", u"Quick start", None))
        self.tag.setText(QCoreApplication.translate("Dialog", u"Tag", None))
        self.cursors.setText(QCoreApplication.translate("Dialog", u"Cursors", None))
    # retranslateUi

